---
- hosts: all
  sudo: yes
  gather_facts: no
  vars:
    noc_ntpserver: server 0.ca.pool.ntp.org

  tasks:

  - name: installs ntp
    apt: name=ntp state=installed update_cache=yes

  - name: writes our ntp.conf
    template: src=/home/vagrant/files/ntp.conf.j2 dest=/etc/ntp.conf mode=644 owner=root group=root
    notify: restart ntp

  - name: starts ntp
    service: name=ntp state=started

  handlers:

  - name: restarts ntp
    service: name=ntp state=restarted
