---
- hosts: web
  tasks:
    - name: Installs NGiNX web server
      apt: pkg=nginx state=installed update_cache=true
      notify:
        - start nginx

    - name: Uploads index.php
      copy: src=static_files/index.php dest=/usr/share/nginx/www/ mode=0644
      register: php
      ignore_errors: True

    - name: Removes index.html
      command: rm /usr/share/nginx/www/index.html
      when: php|success

    - name: Uploads index.html
      copy: src=static_files/index.html dest=/usr/share/nginx/www/ mode=0644
      when: php|failed

  handlers:
    - name: start NGiNX
      service: name=nginx state=started
